name: fig_database_linker
description: A new Flutter package project.
version: 0.0.2
homepage: https://normidar.com

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  mysql1: ^0.17.1
  postgres: ^2.1.1 
  sqflite: ^1.3.0+1
  path: ^1.6.4
